import json

from app.schemas.interview import Evaluation


def parse_evaluation(raw_response: str) -> Evaluation:

    try:
        data = json.loads(raw_response)

        return Evaluation.model_validate(data)

    except (json.JSONDecodeError, ValueError) as exc:
        raise ValueError(
            "Invalid evaluation generated by LLM"
        ) from exc